# Generated by Django 6.1 on 2026-08-22 01:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("workforce", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PlanningAssignment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("work_date", models.DateField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "company",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_assignments",
                        to="organizations.company",
                    ),
                ),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="planning_assignments",
                        to="workforce.employee",
                    ),
                ),
                (
                    "shift",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_assignments",
                        to="workforce.shift",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="planning_assignments",
                        to="workforce.zone",
                    ),
                ),
            ],
            options={
                "ordering": [
                    "work_date",
                    "employee__first_name",
                    "employee__last_name",
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="planningassignment",
            constraint=models.UniqueConstraint(
                fields=("company", "employee", "work_date"),
                name="unique_planning_assignment_per_employee_date",
            ),
        ),
    ]
