# Generated by Django 6.1 on 2026-09-22 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0004_planning_rules'),
    ]

    operations = [
        migrations.AddField(
            model_name='zone',
            name='configured_shifts',
            field=models.ManyToManyField(blank=True, related_name='configured_zones', through='workforce.ZoneShiftPreset', to='workforce.shift'),
        ),
    ]
