# Generated by Django 6.1 on 2026-09-26 16:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0005_add_owner_membership_role'),
        ('workforce', '0008_position_shift_employee_installation_fields'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('start_time_override', models.TimeField(blank=True, null=True)),
                ('end_time_override', models.TimeField(blank=True, null=True)),
                ('break_minutes_override', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_assignments', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='workforce.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workforce.position')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workforce.shift')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='workforce.zone')),
            ],
            options={
                'ordering': ['date', 'employee__first_name', 'employee__last_name'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('weekly_hours', models.DecimalField(decimal_places=2, max_digits=5)),
                ('work_percentage', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('calculation_period', models.CharField(blank=True, max_length=50, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='workforce.employee')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAvailability',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField()),
                ('available', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availabilities', to='workforce.employee')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name', 'day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeAvailabilityException',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('available', models.BooleanField(default=True)),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability_exceptions', to='workforce.employee')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name', 'date', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='EmployeePosition',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('primary', models.BooleanField(default=False)),
                ('proficiency', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_positions', to='workforce.employee')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_positions', to='workforce.position')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name', 'position__name'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeTimeOff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('vacation', 'Vacation'), ('sick', 'Sick leave'), ('personal', 'Personal'), ('other', 'Other')], max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('start_time', models.TimeField(blank=True, null=True)),
                ('end_time', models.TimeField(blank=True, null=True)),
                ('minutes', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], default='requested', max_length=30)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_off_entries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_off_entries', to='workforce.employee')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name', '-start_date'],
            },
        ),
        migrations.CreateModel(
            name='EmployeeZone',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('preferred', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employee_zones', to='workforce.employee')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employee_zones', to='workforce.zone')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name', 'zone__name'],
            },
        ),
        migrations.CreateModel(
            name='Planning',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=30)),
                ('version', models.PositiveIntegerField(blank=True, null=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plannings', to='organizations.installation')),
                ('published_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_plannings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['installation__name', '-start_date', '-version'],
            },
        ),
        migrations.CreateModel(
            name='StaffRequirement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('day_of_week', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('required_employees', models.PositiveIntegerField()),
                ('minimum_employees', models.PositiveIntegerField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('installation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_requirements', to='organizations.installation')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_requirements', to='workforce.position')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_requirements', to='workforce.shift')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_requirements', to='workforce.zone')),
            ],
            options={
                'ordering': ['installation__name', 'date', 'day_of_week', 'zone__name', 'shift__start_time', 'position__name'],
            },
        ),
        migrations.CreateModel(
            name='TimeBalanceEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('accrued', 'Accrued'), ('used', 'Used'), ('adjustment', 'Adjustment')], max_length=30)),
                ('minutes', models.IntegerField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_balance_entries', to='workforce.assignment')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_time_balance_entries', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_balance_entries', to='workforce.employee')),
                ('time_off', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='time_balance_entries', to='workforce.employeetimeoff')),
            ],
            options={
                'ordering': ['employee__first_name', 'employee__last_name', '-date', '-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.UniqueConstraint(fields=('employee', 'date'), name='unique_assignment_per_employee_date'),
        ),
        migrations.AddConstraint(
            model_name='assignment',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time_override__isnull', True), ('start_time_override__isnull', True)), models.Q(('end_time_override__isnull', False), ('start_time_override__isnull', False)), _connector='OR'), name='assignment_override_times_both_null_or_set'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__isnull', True), ('end_date__gte', models.F('start_date')), _connector='OR'), name='contract_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('weekly_hours__gte', 0)), name='contract_weekly_hours_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='contract',
            constraint=models.CheckConstraint(condition=models.Q(('work_percentage__isnull', True), ('work_percentage__lte', 100), _connector='OR'), name='contract_work_percentage_max_100'),
        ),
        migrations.AddConstraint(
            model_name='employeeavailability',
            constraint=models.UniqueConstraint(fields=('employee', 'day_of_week', 'start_time', 'end_time'), name='unique_employee_availability_window'),
        ),
        migrations.AddConstraint(
            model_name='employeeavailability',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), name='valid_availability_day_of_week'),
        ),
        migrations.AddConstraint(
            model_name='employeeavailability',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time__isnull', True), ('start_time__isnull', True)), models.Q(('end_time__isnull', False), ('start_time__isnull', False)), _connector='OR'), name='availability_times_both_null_or_set'),
        ),
        migrations.AddConstraint(
            model_name='employeeavailabilityexception',
            constraint=models.UniqueConstraint(fields=('employee', 'date', 'start_time', 'end_time'), name='unique_employee_availability_exception_window'),
        ),
        migrations.AddConstraint(
            model_name='employeeavailabilityexception',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time__isnull', True), ('start_time__isnull', True)), models.Q(('end_time__isnull', False), ('start_time__isnull', False)), _connector='OR'), name='availability_exception_times_both_null_or_set'),
        ),
        migrations.AddConstraint(
            model_name='employeeposition',
            constraint=models.UniqueConstraint(fields=('employee', 'position'), name='unique_employee_position'),
        ),
        migrations.AddConstraint(
            model_name='employeeposition',
            constraint=models.UniqueConstraint(condition=models.Q(('primary', True)), fields=('employee',), name='unique_primary_position_per_employee'),
        ),
        migrations.AddConstraint(
            model_name='employeetimeoff',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='time_off_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='employeetimeoff',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time__isnull', True), ('start_time__isnull', True)), models.Q(('end_time__isnull', False), ('start_time__isnull', False)), _connector='OR'), name='time_off_times_both_null_or_set'),
        ),
        migrations.AddConstraint(
            model_name='employeezone',
            constraint=models.UniqueConstraint(fields=('employee', 'zone'), name='unique_employee_zone'),
        ),
        migrations.AddConstraint(
            model_name='planning',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='planning_end_date_after_start_date'),
        ),
        migrations.AddConstraint(
            model_name='planning',
            constraint=models.UniqueConstraint(fields=('installation', 'start_date', 'end_date', 'version'), name='unique_planning_period_version'),
        ),
        migrations.AddConstraint(
            model_name='staffrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('day_of_week__isnull', True), models.Q(('day_of_week__gte', 0), ('day_of_week__lte', 6)), _connector='OR'), name='valid_staff_requirement_day_of_week'),
        ),
        migrations.AddConstraint(
            model_name='staffrequirement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('date__isnull', True), ('day_of_week__isnull', False)), models.Q(('date__isnull', False), ('day_of_week__isnull', True)), _connector='OR'), name='staff_requirement_has_day_or_date'),
        ),
        migrations.AddConstraint(
            model_name='staffrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('required_employees__gte', 1)), name='staff_requirement_required_employees_positive'),
        ),
        migrations.AddConstraint(
            model_name='staffrequirement',
            constraint=models.CheckConstraint(condition=models.Q(('minimum_employees__isnull', True), ('minimum_employees__lte', models.F('required_employees')), _connector='OR'), name='staff_requirement_minimum_not_above_required'),
        ),
        migrations.AddConstraint(
            model_name='staffrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('day_of_week__isnull', False)), fields=('installation', 'zone', 'shift', 'position', 'day_of_week'), name='unique_staff_requirement_day_pattern'),
        ),
        migrations.AddConstraint(
            model_name='staffrequirement',
            constraint=models.UniqueConstraint(condition=models.Q(('date__isnull', False)), fields=('installation', 'zone', 'shift', 'position', 'date'), name='unique_staff_requirement_date_pattern'),
        ),
    ]
