# Generated by Django 6.1 on 2026-09-26 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workforce', '0009_assignment_contract_employeeavailability_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='all_zones',
            field=models.BooleanField(default=True, help_text='When true, the employee can work in every zone of the installation.'),
        ),
        migrations.AddField(
            model_name='employee',
            name='availability_unrestricted',
            field=models.BooleanField(default=True, help_text='When true, the employee has no recurring availability restrictions.'),
        ),
    ]
